#!/usr/bin/env python3
import os
import fileinput

def replace_text_in_files(directory):
    for root, dirs, files in os.walk(directory):
        for file_name in files:
            if file_name.endswith('.sub'):
                file_path = os.path.join(root, file_name)
                with fileinput.FileInput(file_path, inplace=True, backup='.bak') as file:
                    for line in file:
                        if 'request_memory = 1 GB' in line:
                            line = line.replace('request_memory = 1 GB', 'Requirements = Machine != "master"')
                        print(line, end='')

if __name__ == '__main__':
    directory = 'testFolder'  # Replace with the actual directory path
    replace_text_in_files(directory)

