#!/bin/bash

# echo 'Running mvp with energy policy'
./mvp -policy performance high -allocator ../Resource_Allocator/allocator -monitoring ../Energy_Monitoring/monitoring -workflow /home/mehul/shared_fs/montage/emwos_half_performance/data/customFolder

-target 
    sustainable high
    balanced
    performance high

# ./mvp -policy performance -allocator ../Resource_Allocator/configurator -monitoring ../Energy_Monitoring/monitoring -workflow /home/mehul/shared_fs/montage/emwos_half_performance/data/emwos-energy