######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : montage, Index = 0, Count = null
# SUBMIT FILE NAME : mDiffFit_ID0001781.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PATH=/usr/bin:/bin:. CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=0102b5ab-8f0e-49d1-9e76-edd4195ecc38 PEGASUS_WF_LABEL=montage PEGASUS_DAG_JOB_ID=mDiffFit_ID0001781 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085//00/06/mDiffFit_ID0001781.err
executable = /home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/00/06/mDiffFit_ID0001781.sh
initialdir = /home/mehul/shared_fs/montage/data/wf-scratch/LOCAL/mehul/pegasus/montage/run0085
log = /home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/montage-0.log
notification = NEVER
output = /home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085//00/06/mDiffFit_ID0001781.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 30
requirements = Machine != "master"
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = region-oversized.hdr,pposs2ukstu_ir_003_001.fits,mDiff,pposs2ukstu_ir_002_006_area.fits,pposs2ukstu_ir_002_006.fits,mFitplane,pposs2ukstu_ir_003_001_area.fits,mDiffFit,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/pegasus-worker-5.0.6-x86_64_deb_11.tar.gz,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/00/00/mProject_ID0001426.meta,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/00/27/stage_in_remote_local_1_1.meta,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/00/27/stage_in_remote_local_1_0.meta,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/00/02/stage_in_remote_local_0_0.meta,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/00/00/mProject_ID0001427.meta,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/00/27/stage_in_remote_local_1_2.meta,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/pegasus-lite-common.sh
transfer_output_files = 3-fit.000012.000013.txt
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "0102b5ab-8f0e-49d1-9e76-edd4195ecc38"
+pegasus_wf_uuid = "0102b5ab-8f0e-49d1-9e76-edd4195ecc38"
+pegasus_version = "5.0.6"
+pegasus_wf_name = "montage-0"
+pegasus_wf_time = "20241107T120130+0000"
+pegasus_wf_xformation = "mDiffFit"
+pegasus_wf_dax_job_id = "ID0001781"
+pegasus_wf_dag_job_id = "mDiffFit_ID0001781"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
