######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : montage, Index = 0, Count = null
# SUBMIT FILE NAME : mBgModel_ID0001375.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PATH=/usr/bin:/bin:. CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=0102b5ab-8f0e-49d1-9e76-edd4195ecc38 PEGASUS_WF_LABEL=montage PEGASUS_DAG_JOB_ID=mBgModel_ID0001375 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085//00/27/mBgModel_ID0001375.err
executable = /home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/00/27/mBgModel_ID0001375.sh
initialdir = /home/mehul/shared_fs/montage/data/wf-scratch/LOCAL/mehul/pegasus/montage/run0085
log = /home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/montage-0.log
notification = NEVER
output = /home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085//00/27/mBgModel_ID0001375.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 50
requirements = Machine != "master"
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = 2-images.tbl,mBgModel,2-fits.tbl,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/pegasus-worker-5.0.6-x86_64_deb_11.tar.gz,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/00/27/mConcatFit_ID0001374.meta,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/00/27/stage_in_remote_local_3_0.meta,/home/mehul/shared_fs/montage/data/mehul/pegasus/montage/run0085/pegasus-lite-common.sh
transfer_output_files = 2-corrections.tbl
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "0102b5ab-8f0e-49d1-9e76-edd4195ecc38"
+pegasus_wf_uuid = "0102b5ab-8f0e-49d1-9e76-edd4195ecc38"
+pegasus_version = "5.0.6"
+pegasus_wf_name = "montage-0"
+pegasus_wf_time = "20241107T120130+0000"
+pegasus_wf_xformation = "mBgModel"
+pegasus_wf_dax_job_id = "ID0001375"
+pegasus_wf_dag_job_id = "mBgModel_ID0001375"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
