#!/bin/bash

while [[ $# -gt 0 ]]; do
  case $1 in
    -node)
      NODE="$2"
      shift 2
      ;;
    -config)
      CONFIG="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

if [ -z "$NODE" ] || [ -z "$CONFIG" ]; then
  echo "Usage: $0 -node <nodename> -config <config>"
  exit 1
fi

echo "Node [$NODE] has been configured. Restarting now."
./resource-configurator -r alpha