######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : montage, Index = 0, Count = null
# SUBMIT FILE NAME : mDiffFit_ID0008946.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PATH=/usr/bin:/bin:. CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=98e10bce-70ca-45aa-bff9-de269a235bd8 PEGASUS_WF_LABEL=montage PEGASUS_DAG_JOB_ID=mDiffFit_ID0008946 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/mehul/shared_fs/montage/twohalf/data/customFolder//00/0A/mDiffFit_ID0008946.err
executable = /home/mehul/shared_fs/montage/twohalf/data/customFolder/00/0A/mDiffFit_ID0008946.sh
initialdir = /home/mehul/shared_fs/montage/twohalf/data/./wf-scratch/LOCAL/mehul/pegasus/montage/run0001
log = /home/mehul/shared_fs/montage/twohalf/data/customFolder/montage-0.log
notification = NEVER
output = /home/mehul/shared_fs/montage/twohalf/data/customFolder//00/0A/mDiffFit_ID0008946.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 30
Requirements = Machine != "master"
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = region-oversized.hdr,mDiff,mFitplane,pposs2ukstu_red_005_010_area.fits,pposs2ukstu_red_007_006_area.fits,mDiffFit,pposs2ukstu_red_005_010.fits,pposs2ukstu_red_007_006.fits,/home/mehul/shared_fs/montage/twohalf/data/customFolder/pegasus-worker-5.0.6-x86_64_deb_11.tar.gz,/home/mehul/shared_fs/montage/twohalf/data/customFolder/01/2D/stage_in_remote_local_1_1.meta,/home/mehul/shared_fs/montage/twohalf/data/customFolder/01/2C/stage_in_remote_local_1_0.meta,/home/mehul/shared_fs/montage/twohalf/data/customFolder/00/06/stage_in_remote_local_0_0.meta,/home/mehul/shared_fs/montage/twohalf/data/customFolder/00/00/mProject_ID0005221.meta,/home/mehul/shared_fs/montage/twohalf/data/customFolder/00/00/mProject_ID0005205.meta,/home/mehul/shared_fs/montage/twohalf/data/customFolder/01/2D/stage_in_remote_local_1_2.meta,/home/mehul/shared_fs/montage/twohalf/data/customFolder/pegasus-lite-common.sh
transfer_output_files = 2-fit.000050.000066.txt
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "98e10bce-70ca-45aa-bff9-de269a235bd8"
+pegasus_wf_uuid = "98e10bce-70ca-45aa-bff9-de269a235bd8"
+pegasus_version = "5.0.6"
+pegasus_wf_name = "montage-0"
+pegasus_wf_time = "20230831T050338+0000"
+pegasus_wf_xformation = "mDiffFit"
+pegasus_wf_dax_job_id = "ID0008946"
+pegasus_wf_dag_job_id = "mDiffFit_ID0008946"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_gpus = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
